### ISSUE TITLE
Establish frequency limits

### ISSUE THREAD

**Issue by ascorzo** [theonlyid/spectral#3]
Since currently, I am working with sleep data and scalp EEG, I think we can save some computational resources by only analyzing a certain interval of frequencies of interest.

**Comment by theonlyid** [comment]
Implementing an f_min, f_max parameter is a great idea! Will do.

**Comment by theonlyid** [comment]
The method contrast() (spectral/src/contrast.py) now accepts fmin, fmax params.

There is also a method for decimating data, decimate(). This can be used when fmax/fs <0.2. This helps optimize the analysis.
